name: Automatización de Datos

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código
    - uses: actions/checkout@v2

    # Paso 2: Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Paso 3: Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas jupyter

    # Paso 4: Convertir y ejecutar Script_Brewery.ipynb
    - name: Ejecutar script principal
      run: |
        jupyter nbconvert --to script Script_Brewery.ipynb
        python Script_Brewery.py

    # Paso 5: Convertir y ejecutar Script_Brewery_errores.ipynb
    - name: Contaminación base datos
      run: |
        jupyter nbconvert --to script Script_Brewery_errores.ipynb
        python Script_Brewery_errores.py

    # Paso 6: Ejecutar limpieza de datos
    - name: Limpieza de datos
      run: |
        python limpieza.py
